language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install codecov
- sudo apt-get install python-nose
script:
- nosetests test.py -v --with-coverage
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)
notification:
email:
recipients:
- cb.hong@ngenebio.com
branches:
only:
- master


