language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"

script:
  - pytest test.py
  - nosetts test.py -v — with-coverage

after_success: 
   - bash <(curl -s https://codecov.io/bash)
