language: python
python:
  - "2.7"

install: 
  - pip install -r requirements.txt
  - pip install codecov

script:
  - pytest test.py
  - pytest --cov=./ test.py

after_success: 
   - codecov
   - bash <(curl -s https://codecov.io/bash)
